build:
  environment:
    php: 7.4

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests:
      environment:
        timezone: FR

      services:
        mysql: 5.7

      tests:
        override:
          - command: composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover

filter:
  excluded_paths:
    - 'tests/*'
